api: true
apiAddress: :9997

hls: false

record: yes
recordPath: /recordings/%path/%Y-%m-%d_%H-%M-%S
recordFormat: fmp4
recordSegmentDuration: 3h

authMethod: http
authHTTPAddress: http://api:3001/v1/internal/mediamtx/auth
authHTTPExclude:
  - action: api

authInternalUsers:
  - user: api
    pass: mediamtxpass
    permissions:
      - action: api

pathDefaults:
  runOnReady: /on-ready.sh
  runOnReadyRestart: no
  runOnNotReady: /on-not-ready.sh
